[package]
name = "my-redis-project"
version = "0.1.0"
edition = "2024"
default-run = "my-redis-project"

[dependencies]
bytes = "1.10.1"
mini-redis = "0.4.1"
tokio = { version = "1.44.1", features = ["full"] }

[[example]]
name = "hello-redis"
path = "examples/hello-redis.rs"

